[build]
  publish = "dist"  # or the folder where your built files are located
  command = "npm run build"  # or the build command for the project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200